"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { trackButtonClick, trackPageView } from "@/lib/analytics";

export default function TermsPage() {
  const router = useRouter();
  const [activeTab, setActiveTab] = React.useState<
    "terms" | "privacy" | "refund"
  >("terms");

  // Track page view on component mount
  React.useEffect(() => {
    trackPageView("/terms", "Terms and Policies Page");
  }, []);

  // Handle tab change
  const handleTabChange = (value: string) => {
    trackButtonClick("policy_tab_switch", value);
    setActiveTab(value as "terms" | "privacy" | "refund");
  };

  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-6 sm:p-12 md:p-24 bg-muted/40">
      <Card className="w-full max-w-4xl shadow-lg">
        <CardHeader className="text-center">
          <CardTitle className="text-3xl sm:text-4xl font-bold">
            Terms and Policies
          </CardTitle>
          <p className="text-muted-foreground mt-2">
            Last Updated: {new Date().toLocaleDateString()}
          </p>
        </CardHeader>
        <CardContent>
          <Tabs
            value={activeTab}
            onValueChange={handleTabChange}
            className="w-full"
          >
            <TabsList className="grid w-full grid-cols-3">
              <TabsTrigger value="terms">Terms of Service</TabsTrigger>
              <TabsTrigger value="privacy">Privacy Policy</TabsTrigger>
              <TabsTrigger value="refund">Refund Policy</TabsTrigger>
            </TabsList>

            <TabsContent value="terms" className="pt-6">
              <div className="space-y-4">
                <h2 className="text-2xl font-semibold">Terms of Service</h2>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">1. Introduction</h3>
                  <p>
                    Welcome to MyKoreanName (&quot;we,&quot; &quot;our,&quot; or
                    &quot;us&quot;). These Terms of Service govern your access
                    to and use of our website, services, and applications
                    (collectively, the &quot;Service&quot;).
                  </p>
                  <p>
                    By using our Service, you agree to be bound by these Terms.
                    If you disagree with any part of these terms, you may not
                    access the Service.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">
                    2. Description of Service
                  </h3>
                  <p>
                    MyKoreanName is a web service that generates Korean names
                    based on users&apos; foreign names. We offer both free and
                    premium services. The free service provides basic features
                    while the premium service offers enhanced features for a
                    fee.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">3. Payment Terms</h3>
                  <p>
                    Premium services are available for a fee. Payment processing
                    is handled by Paddle, a third-party payment processor. By
                    subscribing to a premium service, you agree to the payment
                    terms and conditions set by both us and Paddle. All
                    purchases are final subject to our refund policy.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">
                    4. Intellectual Property
                  </h3>
                  <p>
                    The Korean names generated by our service have no
                    intellectual property restrictions. You may freely use the
                    generated names for any purpose without attribution.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">5. User Content</h3>
                  <p>
                    Any content you submit to the Service, such as your original
                    name, is used solely for the purpose of generating Korean
                    names and is not stored or retained by us beyond what is
                    necessary to provide the Service.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">6. Disclaimer</h3>
                  <p>
                    The Service is provided &quot;as is&quot; without warranties
                    of any kind, either express or implied. We do not guarantee
                    that the names generated will be culturally appropriate in
                    all contexts or that they will be accepted for official
                    purposes in Korea or elsewhere.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">
                    7. Limitation of Liability
                  </h3>
                  <p>
                    To the maximum extent permitted by law, we shall not be
                    liable for any indirect, incidental, special, consequential,
                    or punitive damages resulting from your use of or inability
                    to use the Service.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">8. Changes to Terms</h3>
                  <p>
                    We reserve the right to modify these Terms at any time.
                    Changes will be effective immediately upon posting on the
                    Service. Your continued use of the Service after changes to
                    the Terms constitutes your acceptance of the revised Terms.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">9. Contact Us</h3>
                  <p>
                    If you have any questions about these Terms, please contact
                    us at gguggulab@gmail.com.
                  </p>
                </section>
              </div>
            </TabsContent>

            <TabsContent value="privacy" className="pt-6">
              <div className="space-y-4">
                <h2 className="text-2xl font-semibold">Privacy Policy</h2>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">
                    1. Information Collection
                  </h3>
                  <p>
                    We do not collect or store personal information. The name
                    you input for generating a Korean name is only used
                    temporarily for processing and is not stored after the
                    service is provided.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">2. Cookies</h3>
                  <p>
                    We only use essential cookies required for basic website
                    functionality. We do not use cookies to identify or track
                    users.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">
                    3. Third-Party Services
                  </h3>
                  <p>
                    For payment processing, we may use third-party services like
                    Paddle. In such cases, the privacy policies of those
                    services will apply. We do not access or store information
                    processed by these third-party services.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">4. Analytics</h3>
                  <p>
                    We use Google Analytics to monitor and analyze the use of
                    our Service. Google Analytics collects standard internet log
                    information and visitor behavior information in an
                    anonymized form. This information is processed to generate
                    statistical reports on website activity. No personally
                    identifiable information is collected through Google
                    Analytics. The data collected by Google is subject to
                    Google&apos;s Privacy Policy.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">
                    5. Changes to Privacy Policy
                  </h3>
                  <p>
                    This Privacy Policy may be updated as necessary. Any changes
                    will be effective immediately upon posting on this website.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">6. Contact Us</h3>
                  <p>
                    If you have any questions about this Privacy Policy, please
                    contact us at gguggulab@gmail.com.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">
                    8. Children&apos;s Privacy
                  </h3>
                  <p>
                    Our Service does not address anyone under the age of 13. We
                    do not knowingly collect personally identifiable information
                    from children under 13. If you are a parent or guardian and
                    you are aware that your child has provided us with personal
                    information, please contact us.
                  </p>
                </section>
              </div>
            </TabsContent>

            <TabsContent value="refund" className="pt-6">
              <div className="space-y-4">
                <h2 className="text-2xl font-semibold">Refund Policy</h2>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">
                    1. Premium Service Refunds
                  </h3>
                  <p>
                    We strive to provide high-quality Korean name generation
                    services. However, if you are not satisfied with our premium
                    service, you may be eligible for a refund under certain
                    conditions.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">2. Refund Eligibility</h3>
                  <p>
                    You may be eligible for a refund of your premium service
                    payment if:
                  </p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>
                      The service fails to generate a Korean name due to
                      technical issues on our end
                    </li>
                    <li>
                      You request a refund within 24 hours of purchase and have
                      not used the premium service features
                    </li>
                    <li>
                      You are charged multiple times for the same service due to
                      a technical error
                    </li>
                  </ul>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">
                    3. Non-Refundable Circumstances
                  </h3>
                  <p>Refunds will not be issued in the following cases:</p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>
                      You are not satisfied with the generated Korean name
                    </li>
                    <li>You have used the premium service features</li>
                    <li>
                      Your request is made more than 24 hours after purchase
                    </li>
                    <li>
                      The service was provided as described but did not meet
                      your expectations
                    </li>
                  </ul>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">4. Refund Process</h3>
                  <p>
                    To request a refund, please contact us at
                    gguggulab@gmail.com with the following information:
                  </p>
                  <ul className="list-disc pl-6 space-y-1">
                    <li>Your full name</li>
                    <li>Email address used for the purchase</li>
                    <li>
                      Date and approximate time of purchase (including your
                      timezone)
                    </li>
                    <li>Transaction ID (if available)</li>
                    <li>Reason for refund request</li>
                  </ul>
                  <p>
                    We will review your request and respond within 5 business
                    days. If your refund is approved, the refund will be
                    processed through the same payment method used for the
                    original transaction.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">5. Processing Time</h3>
                  <p>
                    Approved refunds will be processed within 5-10 business
                    days, but the actual time it takes for the refund to appear
                    in your account depends on your payment provider.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">
                    6. Changes to This Refund Policy
                  </h3>
                  <p>
                    We reserve the right to update or change our Refund Policy
                    at any time. Any changes will be effective immediately upon
                    posting on this page.
                  </p>
                </section>

                <section className="space-y-2">
                  <h3 className="text-xl font-medium">7. Contact Us</h3>
                  <p>
                    If you have any questions about this Refund Policy, please
                    contact us at gguggulab@gmail.com.
                  </p>
                </section>
              </div>
            </TabsContent>
          </Tabs>

          <div className="mt-8 flex justify-center">
            <Button
              onClick={() => {
                trackButtonClick("return_to_home", "from_terms_page");
                router.push("/");
              }}
              className="px-8"
            >
              Return to Home
            </Button>
          </div>
        </CardContent>
      </Card>
    </main>
  );
}
